runner:
  debug: False
  cp_path: "/work/b08202033/multilingual_zero_resource_challenge/xlsr2_960m_1000k.pt"
  resume: False
  strict: True
  cpu: False
  pathClusteringCheckpoint: '/work/b08202033/zerospeech2021_baseline/checkpoints/half_cs_half_mono_kmeans_75cluster_30iter/kmeans_30iter.pt'
  s3prl: null
  layer: -1
data:
  file_extension: ['flac', 'wav']
  pathSeq: null
  split: null
  max_size_seq: 10240
  batch_size: 16
  pathDB: [ "/work/b08202033/zerospeech2021_baseline/datasets/cs_16k/wav/es_en/dev/correct",
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_16k/wav/fr_en/dev/correct",
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_16k/wav/zh_en/dev/correct"
          ]
  
