cs:
  data_root: "/work/gerber68/Data/cs_mono/wav/"
  lang: ["es_en", "fr_en", "zh_en"]
  hr: [34, 34, 32]
  output: "/work/gerber68/Data/cs_mono_sampled/wav/"

mono:
  data_root: "/work/gerber68/Data/mono/"
  lang: ["mls_spanish", "mls_freanch", "train", "train-clean-100"]
  ext: ["flac", "flac", "wav", "flac"] 
  hr: [25, 25, 25, 25]
  output: "/work/gerber68/Data/mono_sampled/25hr/"

