cs_data_root: "/work/b08202033/multilingual_zero_resource_challenge/datasets/cs_mono/wav"
lang: ["es_en", "fr_en", "zh_en"]
hr: [34, 34, 32]
output: "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_sampled/wav"