runner:
  pathOutput: "/work/b08202033/zerospeech2021_baseline/checkpoints/debug/kmeans_30iter.pt"
  nClusters: 100
  nGroups: 1
  debug: False
  encoder_layer: False
  level_gru: None
  DPMean: False
  DPLambda: 11
  perIterSize: -1
  train_mode: False
  dimReduction: null
  centroidLimits: null
  getDistanceEstimation: False
  MAX_ITER: 5
  save: True
  load: True
  save_last: 5
  cp_path: null
  epsilon: 0.0001
  s3prl: hubert
  layer: -1 # -1 for last layer


data:
  recursionLevel: 1
  extension: ['.flac', '.wav']
  seqList: null
  sizeWindow: 10240
  batchSizeGPU: 80
  pathDB: [ "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total_16k/wav/es_en/train/correct",
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total_16k/wav/fr_en/train/correct",
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total_16k/wav/zh_en/train/correct",
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total/mls_french", 
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total/mls_spanish", 
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total/train", 
            "/work/b08202033/zerospeech2021_baseline/datasets/cs_mono_mix/50_total/train-clean-100"
          ]
  
