common:
  fp16: true
  log_format: json
  log_interval: 50
  wandb_project: ???

checkpoint:
  no_epoch_checkpoints: true
  #finetune_from_model: /work/b08202033/multilingual_zero_resource_challenge/xlmr.base/model.pt

task:
  _name: masked_lm
  data: ???
  sample_break_mode: complete
  tokens_per_sample: 512

criterion: masked_lm

dataset:
  batch_size: 32
  ignore_unused_valid_subsets: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 500

optimization:
  clip_norm: 0
  lr: [0.0001]
  max_update: 5000
  update_freq: [8]

model:
  _name: roberta_base
  max_positions: 512
  dropout: 0.1
  attention_dropout: 0.1