runner:
  debug: False
  cp_path: "/work/b08202033/multilingual_zero_resource_challenge/xlsr2_960m_1000k.pt"
  resume: False
  strict: True
  cpu: False

data:
  file_extension: ['flac', 'wav']
  pathSeq: null
  split: null
  max_size_seq: 10240
  batch_size: 8
  pathDB: ["/work/b08202033/multilingual_zero_resource_challenge/datasets/cs_mono/wav/en_zh/train/correct", "/work/b08202033/multilingual_zero_resource_challenge/datasets/cs_mono/wav/es_en/train/correct", 
            "/work/b08202033/multilingual_zero_resource_challenge/datasets/cs_mono/wav/fr_en/train/correct", "/work/b08202033/multilingual_zero_resource_challenge/datasets/cs_mono/wav/zh_en/train/correct"]
  
